### ISSUE TITLE
IndexOutOfBoundsException: getChars (59 ... 60) ends beyond length 59

### ISSUE THREAD

**Issue by wisnukurniawan** [yydcdut/RxMarkdown#21]
this error happen when i type text in edittext and then I delet the text

`java.lang.IndexOutOfBoundsException: getChars (59 ... 60) ends beyond length 59
                      at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1018)
                      at android.text.SpannableStringBuilder.getChars(SpannableStringBuilder.java:915)
                      at android.text.TextUtils.getChars(TextUtils.java:81)
                      at android.text.SpannableStringBuilder.<init>(SpannableStringBuilder.java:64)
                      at android.text.SpannableStringBuilder.subSequence(SpannableStringBuilder.java:907)
                      at com.yydcdut.rxmarkdown.edit.BlockQuotesController.onTextChanged(BlockQuotesController.java:74)
                      at com.yydcdut.rxmarkdown.RxMDEditText.onTextChanged4Controller(RxMDEditText.java:291)
                      at com.yydcdut.rxmarkdown.RxMDEditText.access$900(RxMDEditText.java:54)
                      at com.yydcdut.rxmarkdown.RxMDEditText$EditTextWatcher.onTextChanged(RxMDEditText.java:212)
                      at android.widget.TextView.sendOnTextChanged(TextView.java:7704)
                      at android.widget.TextView.handleTextChanged(TextView.java:7764)
                      at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:9481)
                      at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:964)
                      at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:515)
                      at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:454)
                      at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:33)
                      at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:685)
                      at android.view.inputmethod.BaseInputConnection.setComposingText(BaseInputConnection.java:445)
                      at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:340)
                      at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:135)
                      at android.app.ActivityThread.main(ActivityThread.java:5319)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)`

**Comment by yydcdut** [comment]
fix. try 0.0.9-beta.
