### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by jemshit** [yydcdut/RxMarkdown#51]
```
java.lang.ArrayIndexOutOfBoundsException: length=6; index=6
        at com.yydcdut.markdown.syntax.text.ImageSyntax.contains(ImageSyntax.java:97)
        at com.yydcdut.markdown.syntax.text.ImageSyntax.isMatch(ImageSyntax.java:54)
        at com.yydcdut.markdown.syntax.text.TextSyntaxAdapter.isMatch(TextSyntaxAdapter.java:57)
        at com.yydcdut.markdown.chain.MultiSyntaxChain.handleSyntax(MultiSyntaxChain.java:45)
        at com.yydcdut.markdown.chain.SyntaxMultiChains.handleSyntax(SyntaxMultiChains.java:53)
        at com.yydcdut.markdown.chain.SyntaxDoElseChain.handleSyntax(SyntaxDoElseChain.java:58)
        at com.yydcdut.markdown.chain.SyntaxDoElseChain.handleSyntax(SyntaxDoElseChain.java:58)
        at com.yydcdut.markdown.chain.SyntaxDoElseChain.handleSyntax(SyntaxDoElseChain.java:58)
        at com.yydcdut.markdown.chain.SyntaxChain.handleSyntax(SyntaxChain.java:49)
        at com.yydcdut.markdown.syntax.text.TextFactory.parseByLine(TextFactory.java:210)
        at com.yydcdut.markdown.syntax.text.TextFactory.parse(TextFactory.java:193)
        at com.yydcdut.markdown.MarkdownProcessor.parse(MarkdownProcessor.java:32)
```

Version:0.1.2-alpha
Android emulator: v8.0
SDK 27

Code:
```kotlin
val markdownProcessor = MarkdownProcessor(context)
markdownProcessor.factory(TextFactory.create())
//markdownProcessor.config(MarkdownConfiguration.Builder(context!!).build())
text_content.text = markdownProcessor.parse("Abc \\!")
```

**Comment by jemshit** [comment]
👍
